### ISSUE TITLE
Issue when output nodes are stuck-at-0

### ISSUE THREAD

**Issue by vkrao100** [d-kfmnn/amulet2#2]
Hi Daniela,

Great tool and concept. 

I see an issue with the tool throwing a segmentation exception when any output node is stuck-at-0 (wiring fault).
Attached a test case for the same (aig and blif).
[test_case_s-a-0.zip](https://github.com/d-kfmnn/amulet2/files/6474117/test_case_s-a-0.zip)

Thanks,
Vikas
University of Utah

**Comment by vkrao100** [comment]
d-kfmnn

**Comment by d-kfmnn** [comment]
Hi Vikas, 

thank you for reaching out. 
I don't immediately see  what's causing the issue. Let me check it out. 

Thanks for the test case.
Best Daniela

**Comment by d-kfmnn** [comment]
Hi Vikas, 

there were some exceptions missing for the case when an output is not wired. The issue should now be fixed. 

Best Daniela
