### ISSUE TITLE
Issue with amulet2.0 generating remainder in primary inputs only

### ISSUE THREAD

**Issue by vkrao100** [d-kfmnn/amulet2#3]
I was trying to run another test case with an internal node s-a-0. I see that amulet1.0 and amulet1.5 are able to generate the correct remainders in terms of primary inputs only. However, amulet2.0 generates a remainder in terms of non-primary inputs for the exact same test case. 

Attached the test case (blif/aig)

[4-bit-n18-sa-0.zip](https://github.com/d-kfmnn/amulet2/files/6474166/4-bit-n18-sa-0.zip)

**Comment by vkrao100** [comment]
@d-kfmnn

**Comment by d-kfmnn** [comment]
In amulet2.0 I use a different ordering method than in amulet1.x 
Thanks again for the test case. I'll check out what causes the problems.

Best, Daniela

**Comment by d-kfmnn** [comment]
Hi,

indeed the new ordering in AMulet2 broke on your example, which is now fixed.
Daniela
