### ISSUE TITLE
Issue with output stuck-at-1

### ISSUE THREAD

**Issue by vkrao100** [d-kfmnn/amulet2#4]
Hi @d-kfmnn,

Thank you for actively fixing the 2 raised issues. Meanwhile, I think the issue with the output node stuck-at-faults still persists and I see that it fails for cases when the output node is stuck-at-1.

Code fails at (gate.cpp).mark_aig_outputs(), probably the exception condition (!lit) isn't sufficient to check for stuck-at-1.

Attaching a test case.
[4_bit_cf1.zip](https://github.com/d-kfmnn/amulet2/files/6503466/4_bit_cf1.zip)

Thanks,
Vikas

**Comment by d-kfmnn** [comment]
Hi Vikas,

thanks again for so patiently reporting the issues! 
And yes, my fix from yesterday only covered the case for constant 0. Now it can also deal with constant 1. I also tested now some test cases when internal nodes receive a constant as input. So I these cases should not lead to segfaults any more. 

Thanks, Daniela
